RabbitMqToBlobUploaderJob:
    LogsConnString:
        settings-key: RabbitMqToBlobUploaderJob-LogsConnString
        types:
            - AzureTableStorage
    BlobConnectionString:
        settings-key: RabbitMqToBlobUploaderJob-BlobConnectionString
        types:
            - AzureTableStorage
    IsPublicContainer: false
    CompressData:
        settings-key: RabbitMqToBlobUploaderJob-CompressData
    ContainerName:
        settings-key: RabbitMqToBlobUploaderJob-ContainerName
    UseBatchingByHour:
        settings-key: RabbitMqToBlobUploaderJob-UseBatchingByHour
    MinBatchCount: 10
    MaxBatchCount: 1000
    Rabbit:
        ConnectionString:
            settings-key: RabbitMqToBlobUploaderJob-RabbitMqConnectionString
            types:
                - RabbitMq
        ExchangeName:
            settings-key: RabbitMqToBlobUploaderJob-ExchangeName
        RoutingKey:
            settings-key: RabbitMqToBlobUploaderJob-RoutingKey
            types:
                - Optional

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl

SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName: 
            settings-key: SlackQueueName